---
abstract: 'a plugin for adding Ajax route handlers'
author:
  - 'Dancer Core Developers'
build_requires:
  Dancer2: 0.155000
  ExtUtils::MakeMaker: 0
  File::Spec: 0
  HTTP::Request::Common: 0
  IO::Handle: 0
  IPC::Open3: 0
  Module::Build: 0.28
  Plack::Test: 0
  Test::More: 0.92
  perl: 5.006
configure_requires:
  ExtUtils::MakeMaker: 0
  Module::Build: 0.28
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.025, CPAN::Meta::Converter version 2.142690'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dancer2-Plugin-Ajax
provides:
  Dancer2::Plugin::Ajax:
    file: lib/Dancer2/Plugin/Ajax.pm
    version: 0.200000
requires:
  Dancer2: 0.155000
  Dancer2::Plugin: 0
  strict: 0
  warnings: 0
resources:
  IRC: irc://irc.perl.org/#dancer
  WebIRC: https://chat.mibbit.com/#dancer@irc.perl.org
  bugtracker: https://github.com/PerlDancer/Dancer2-Plugin-Ajax/issues
  homepage: https://github.com/PerlDancer/Dancer2-Plugin-Ajax
  repository: https://github.com/PerlDancer/Dancer2-Plugin-Ajax.git
version: 0.200000
